### ISSUE TITLE
There is no classifying folder for OPS related files.

### ISSUE THREAD

**Issue by ToasturBruh** [SirMetaladon/gmtb-operations#1]
Files related to OPS are not easy to follow, there are generic folders such as 'worlds' or 'oldreleases' that don't make any sense on their own and may be hard to distinguish (and possibly annoying if somebody has folders by the same name).

**Comment by SirMetaladon** [comment]
Fixed. Thanks for the suggestion, all E2s and Dupes are moved to gmtb_operations. Should keep things cleaner!
